/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

/**
 *
 * @author laboratorio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMcadastrar = new javax.swing.JMenu();
        jMcadAluno = new javax.swing.JMenuItem();
        jMcadProf = new javax.swing.JCheckBoxMenuItem();
        jMcadDisc = new javax.swing.JCheckBoxMenuItem();
        jMdelProfessor = new javax.swing.JMenu();
        jMdelAluno = new javax.swing.JMenuItem();
        jMdelProf = new javax.swing.JCheckBoxMenuItem();
        jMdelDisc = new javax.swing.JCheckBoxMenuItem();
        jMeditar = new javax.swing.JMenu();
        jMedAluno = new javax.swing.JMenuItem();
        jMedProf = new javax.swing.JMenuItem();
        jMediDisc = new javax.swing.JMenuItem();
        jMrelatorios = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jClistProf = new javax.swing.JCheckBoxMenuItem();
        jMdisc = new javax.swing.JMenuItem();
        jMgeral = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(560, 240));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ESCOLA ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText(" CAMINHO RADICAL");

        jMcadastrar.setText("Cadastrar");

        jMcadAluno.setText("Cadastro Aluno");
        jMcadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcadAlunoActionPerformed(evt);
            }
        });
        jMcadastrar.add(jMcadAluno);

        jMcadProf.setText("Cadastrar Professor");
        jMcadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcadProfActionPerformed(evt);
            }
        });
        jMcadastrar.add(jMcadProf);

        jMcadDisc.setText("Cadastrar Disciplina");
        jMcadDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcadDiscActionPerformed(evt);
            }
        });
        jMcadastrar.add(jMcadDisc);

        jMenuBar1.add(jMcadastrar);

        jMdelProfessor.setText("Deletar");

        jMdelAluno.setText("Deletar Aluno");
        jMdelAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMdelAlunoActionPerformed(evt);
            }
        });
        jMdelProfessor.add(jMdelAluno);

        jMdelProf.setText("Deletar Professor");
        jMdelProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMdelProfActionPerformed(evt);
            }
        });
        jMdelProfessor.add(jMdelProf);

        jMdelDisc.setText("Deletar Disciplina");
        jMdelDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMdelDiscActionPerformed(evt);
            }
        });
        jMdelProfessor.add(jMdelDisc);

        jMenuBar1.add(jMdelProfessor);

        jMeditar.setText("Editar");

        jMedAluno.setText("Editar Aluno");
        jMedAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedAlunoActionPerformed(evt);
            }
        });
        jMeditar.add(jMedAluno);

        jMedProf.setText("Editar Professor");
        jMedProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedProfActionPerformed(evt);
            }
        });
        jMeditar.add(jMedProf);

        jMediDisc.setText("Editar Disciplina");
        jMediDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMediDiscActionPerformed(evt);
            }
        });
        jMeditar.add(jMediDisc);

        jMenuBar1.add(jMeditar);

        jMrelatorios.setText("Relatorios");

        jMenuItem3.setText("Alunos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMrelatorios.add(jMenuItem3);

        jClistProf.setText("Professores");
        jClistProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClistProfActionPerformed(evt);
            }
        });
        jMrelatorios.add(jClistProf);

        jMdisc.setText("Disciplinas");
        jMdisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMdiscActionPerformed(evt);
            }
        });
        jMrelatorios.add(jMdisc);

        jMgeral.setText("Geral");
        jMgeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMgeralActionPerformed(evt);
            }
        });
        jMrelatorios.add(jMgeral);

        jMenuBar1.add(jMrelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMdelAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMdelAlunoActionPerformed
        // TODO add your handling code here:
        FormDeletarAluno d = new FormDeletarAluno();
        d.show();
    }//GEN-LAST:event_jMdelAlunoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         FormLista d = new FormLista();
        d.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMcadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcadProfActionPerformed
        // TODO add your handling code here:
        FrCadProf cp = new FrCadProf();
        cp.show();
    }//GEN-LAST:event_jMcadProfActionPerformed

    private void jMcadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcadAlunoActionPerformed
        // TODO add your handling code here:
        CadastroAluno ca = new CadastroAluno();
        ca.show();
    }//GEN-LAST:event_jMcadAlunoActionPerformed

    private void jMcadDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcadDiscActionPerformed
        // TODO add your handling code here:
        FrCadDisc cd = new FrCadDisc();
        cd.show();
    }//GEN-LAST:event_jMcadDiscActionPerformed

    private void jMdelDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMdelDiscActionPerformed
        // TODO add your handling code here:
        FrDelDisc dd = new FrDelDisc();
        dd.show();
    }//GEN-LAST:event_jMdelDiscActionPerformed

    private void jMedAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedAlunoActionPerformed
        // TODO add your handling code here:
        FrAtualizar aa = new FrAtualizar();
        aa.show();
    }//GEN-LAST:event_jMedAlunoActionPerformed

    private void jMdelProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMdelProfActionPerformed
        // TODO add your handling code here:
        FrDelProf dp = new FrDelProf();
        dp.show();
    }//GEN-LAST:event_jMdelProfActionPerformed

    private void jMedProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedProfActionPerformed
        // TODO add your handling code here:
        FrAtuProf ap = new FrAtuProf();
        ap.show();
    }//GEN-LAST:event_jMedProfActionPerformed

    private void jMediDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMediDiscActionPerformed
        // TODO add your handling code here:
        FrAtuDisc ad = new FrAtuDisc();
        ad.show();
    }//GEN-LAST:event_jMediDiscActionPerformed

    private void jClistProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClistProfActionPerformed
        // TODO add your handling code here:
        FrlistProf lp = new FrlistProf();
        lp.show();
    }//GEN-LAST:event_jClistProfActionPerformed

    private void jMdiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMdiscActionPerformed
        // TODO add your handling code here:
        FrListDisc ld = new FrListDisc();
        ld.show();
    }//GEN-LAST:event_jMdiscActionPerformed

    private void jMgeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMgeralActionPerformed
        // TODO add your handling code here:
        FrListGeral lg = new FrListGeral();
        lg.show();
    }//GEN-LAST:event_jMgeralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jClistProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMcadAluno;
    private javax.swing.JCheckBoxMenuItem jMcadDisc;
    private javax.swing.JCheckBoxMenuItem jMcadProf;
    private javax.swing.JMenu jMcadastrar;
    private javax.swing.JMenuItem jMdelAluno;
    private javax.swing.JCheckBoxMenuItem jMdelDisc;
    private javax.swing.JCheckBoxMenuItem jMdelProf;
    private javax.swing.JMenu jMdelProfessor;
    private javax.swing.JMenuItem jMdisc;
    private javax.swing.JMenuItem jMedAluno;
    private javax.swing.JMenuItem jMedProf;
    private javax.swing.JMenuItem jMediDisc;
    private javax.swing.JMenu jMeditar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMgeral;
    private javax.swing.JMenu jMrelatorios;
    // End of variables declaration//GEN-END:variables
}
